# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/taller_nvdeb',
                'doc_host': 'https://edwin672.github.io',
                'git_url': 'https://github.com/edwin672/taller_nvdeb',
                'lib_path': 'taller_nvdeb'},
  'syms': {'taller_nvdeb.core': {'taller_nvdeb.core.foo': ('core.html#foo', 'taller_nvdeb/core.py')}}}
