# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../nbs/00_core.ipynb 3
def foo(var_bool):
    "Esta funcion muestra un mensaje dependiendo del valor de la variable de entrada"
    if var_bool:
        return "verdadero"
    else:
        return "falso"
    return
    
